#define STATUS_1 "POWER: "
#define ARMED_1 "ARMED: "

#define NO_CONNECTION "ERROR: NO CONN"

#define OFFMESSAGE "OFF"
#define ONMESSAGE "ON"
#define SENDINGMESSAGE "SENDING"

#define GPS "GPS: "
#define GPSFIX "FIX:"
#define ALTITUDE "ALT:"
#define APOGEE "APOGEE: "
#define DEPLOY "DEPLOY:"
#define CHUTE " CHUTE:"
#define LANDED "LANDED:"
#define TEMP0 "TEMP: "
#define TEMP1 "GOPRO: "
#define TEMP2 "OUT: "
#define TEMP3 "IN: "
#define VERTSPEED "SPD:" 
#define ACCELERATION "ACC: "
#define LIGHT "IL:"

#define THERM_DATA_FILENAME "Thermistor"
#define LIGHT_DATA_FILENAME "AmbientLight"
#define ACC_DATA_FILENAME "Accelerometer"
#define GYRO_DATA_FILENAME "Gyroscope"
#define PRESSURE_DATA_FILENAME "PressureSensor"
#define GPS_DATA_FILENAME "GPSCoords"

#define CONN1 "SD1:"
#define CONN2 "SD2:"
#define CONN3 "CS:"
#define CONN4 "INT:"
#define CONN5 "ALT:"
