update=2018-04-05 9:19:44 PM
version=1
last_client=kicad
[cvpcb]
version=1
NetIExt=net
[general]
version=1
[schematic_editor]
version=1
PageLayoutDescrFile=
PlotDirectoryName=
SubpartIdSeparator=0
SubpartFirstId=65
NetFmtName=
SpiceForceRefPrefix=0
SpiceUseNetNumbers=0
LabSize=60
[pcbnew]
version=1
PageLayoutDescrFile=
LastNetListRead=Recovery Board.net
PadDrill=0.762
PadDrillOvalY=0.762
PadSizeH=1.524
PadSizeV=1.524
PcbTextSizeV=1.5
PcbTextSizeH=1.5
PcbTextThickness=0.3
ModuleTextSizeV=1
ModuleTextSizeH=1
ModuleTextSizeThickness=0.15
SolderMaskClearance=0.2
SolderMaskMinWidth=0
DrawSegmentWidth=0.2
BoardOutlineThickness=0.15
ModuleOutlineThickness=0.15
[eeschema]
version=1
LibDir=../Instrumentation Board;../libs/Schematic parts
[eeschema/libraries]
LibName1=Recovery Board-rescue
LibName2=power
LibName3=device
LibName4=switches
LibName5=relays
LibName6=motors
LibName7=transistors
LibName8=conn
LibName9=linear
LibName10=regul
LibName11=74xx
LibName12=cmos4000
LibName13=adc-dac
LibName14=memory
LibName15=xilinx
LibName16=microcontrollers
LibName17=dsp
LibName18=microchip
LibName19=analog_switches
LibName20=motorola
LibName21=texas
LibName22=intel
LibName23=audio
LibName24=interface
LibName25=digital-audio
LibName26=philips
LibName27=display
LibName28=cypress
LibName29=siliconi
LibName30=opto
LibName31=atmel
LibName32=contrib
LibName33=valves
LibName34=a2135-h
LibName35=arduino_nano
LibName36=fgpmmopa6h
LibName37=sot-223
LibName38=C:/Users/paula/OneDrive/Documents/Placeholders
LibName39=Recovery Board Parts
LibName40=libs/Schematic parts/a2135-h
LibName41=libs/Schematic parts/ap2204k-5
LibName42=libs/Schematic parts/arduino_nano
LibName43=libs/Schematic parts/fgpmmopa6h
LibName44=libs/Schematic parts/Recovery Board Parts
LibName45=libs/Schematic parts/Recovery Board-cache
LibName46=libs/Schematic parts/sot-223
LibName47=D:/Rocketry/Payload Repo/PCBs/libs/Schematic parts/a2135-h
LibName48=D:/Rocketry/Payload Repo/PCBs/libs/Schematic parts/ap2204k-5
LibName49=D:/Rocketry/Payload Repo/PCBs/libs/Schematic parts/arduino_nano
LibName50=D:/Rocketry/Payload Repo/PCBs/libs/Schematic parts/fgpmmopa6h
LibName51=D:/Rocketry/Payload Repo/PCBs/libs/Schematic parts/Recovery Board Parts
LibName52=D:/Rocketry/Payload Repo/PCBs/libs/Schematic parts/Recovery Board-cache
LibName53=D:/Rocketry/Payload Repo/PCBs/libs/Schematic parts/sot-223
LibName54=instrumentation_board_parts
LibName55=instrumentation_board-cache
